### ISSUE TITLE
Port the existing theme to Hugo.

### ISSUE THREAD

**Issue by UtkarshVerma** [WebOpsIIITDMK/vidhai#1]
Since the website's going to be static, we'll be porting the existing website to [Hugo](https://gohugo.io).
The current website is https://michaelscofield1405.github.io/Vidhai-iiitdm.

**Comment by anuragdevon** [comment]
> Since the website's going to be static, we'll be porting the existing website to [Hugo](https://gohugo.io).
> The current website is https://michaelscofield1405.github.io/Vidhai-iiitdm.

Agree

**Comment by UtkarshVerma** [comment]
Porting done. Only the frontend portion is remaining.
